version: "3.9"

services:
  redpanda:
    container_name: user_mgmt_svc_redpanda
    image: redpandadata/redpanda:v24.1.8
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --check=false
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr redpanda:9092   # critical change
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - rpdata:/var/lib/redpanda/data
    networks:
      - kafka-net
      - user_mgmt_dev

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: user_mgmt_svc_kafka_ui
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:9092   # ✅ matches advertised address
    depends_on:
      - redpanda
    networks:
      - kafka-net
      - user_mgmt_dev

  console:
    image: redpandadata/console:latest
    container_name: user_mgmt_svc_console
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: "redpanda:9092"   # ✅ internal Docker DNS resolution
    depends_on:
      - redpanda
    networks:
      - kafka-net
      - user_mgmt_dev

volumes:
  rpdata:

networks:
  kafka-net:
    driver: bridge
  user_mgmt_dev:
    driver: bridge
